db_store:
    build: ./db_store/dockerconf/
    image: erl-odbc:v1.1
    container_name: db_store
    hostname: db_store
    working_dir: /var/db_store
    volumes:
      - ./db_store:/var/db_store
      - /var/maxwin/conf/db_store/freetds.conf:/etc/freetds/freetds.conf
      - /usr/share/zoneinfo/Asia/Taipei:/usr/share/zoneinfo/Asia/Taipei
      - /usr/share/zoneinfo/Asia/Taipei:/etc/localtime/
      - ./db_store/dockerconf/odbc.ini:/etc/odbc.ini
    ports:
      - 9500:9500
    command: ["./dbstore.sh"]
    #command: ["/bin/sh", "-c", "while true; do echo hello world; sleep 1000; done"]
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
